spring:
  main:
    banner-mode: "off"
  application:
    name: concordia-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

management:
  endpoint:
    health:
      access: read_only

springdoc:
  default-produces-media-type: application/json
  use-fqn: true
